apiVersion: tekton.dev/v1beta1
kind: Pipeline
metadata:
  name: retry-example
spec:
  tasks:
  - name: retry-me
    retries: 5
    taskSpec:
      steps:
      - image: alpine:3.12.0
        script: |
          #!/usr/bin/env sh
          if [ "$(context.task.retry-count)" == "$(context.pipelineTask.retries)" ]; then
            echo "This is the last retry."
            exit 0;
          fi
          echo "The PipelineTask has retried $(context.task.retry-count) times."
          exit 1
  - name: hello-world
    runAfter:
      - retry-me
    taskSpec:
      steps:
        - image: busybox
          script: |
            echo "hello world"
---
apiVersion: tekton.dev/v1beta1
kind: PipelineRun
metadata:
  name: retry-example-run
spec:
  pipelineRef:
    name: retry-example
  serviceAccountName: 'default'
